[build]
  publish = "dist"
  # Directory containing the serverless functions
  functions = "api"

[dev]
  # Command to start your frontend development server
  command = "yarn dev" # or "npm run dev"
  # Port for the Netlify Dev server itself (proxying to your frontend and functions)
  port = 3000
  # Port for the Netlify Functions server
  functionsPort = 8888
  # Explicitly tell Netlify Dev the port your frontend framework (Vite) is running on
  targetPort = 5173

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200