[build]
  # Directory containing the serverless functions
  functions = "api"

[dev]
  # Command to start your frontend development server
  command = "yarn dev" # or "npm run dev"
  # Port for the frontend server
  port = 3002
  # Port for the Netlify Functions server
  functionsPort = 8888
  # Tells netlify dev TO use Vite's proxy if configured
  # (often needed if proxy targets aren't automatically detected)
  # targetPort = 5173 # Use if auto-detection fails