

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."trigger_set_timestamp"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."trigger_set_timestamp"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."blocks_overview" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "airtable_record_id" "text" NOT NULL,
    "public_name" "text",
    "rest_between_sets" "text",
    "intensity" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."blocks_overview" OWNER TO "postgres";


COMMENT ON COLUMN "public"."blocks_overview"."airtable_record_id" IS 'Original Airtable Record ID for sync purposes';



CREATE TABLE IF NOT EXISTS "public"."exercise_library" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "airtable_record_id" "text" NOT NULL,
    "current_name" "text",
    "vimeo_code" "text",
    "equipment_public_name" "text",
    "over_sort_category" "text",
    "explanation_1" "text",
    "explanation_2" "text",
    "explanation_3" "text",
    "explanation_4" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."exercise_library" OWNER TO "postgres";


COMMENT ON COLUMN "public"."exercise_library"."airtable_record_id" IS 'Original Airtable Record ID for sync purposes';



CREATE TABLE IF NOT EXISTS "public"."individual_blocks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "airtable_record_id" "text" NOT NULL,
    "block_overview_id" "uuid",
    "airtable_block_overview_record_id" "text",
    "exercise_id" "uuid",
    "airtable_exercise_record_id" "text",
    "sets" integer,
    "reps" integer,
    "sets_and_reps_text" "text",
    "unit" "text",
    "special_instructions" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."individual_blocks" OWNER TO "postgres";


COMMENT ON COLUMN "public"."individual_blocks"."airtable_record_id" IS 'Original Airtable Record ID for sync purposes';



COMMENT ON COLUMN "public"."individual_blocks"."airtable_block_overview_record_id" IS 'Original Airtable Record ID of the parent Blocks Overview record';



COMMENT ON COLUMN "public"."individual_blocks"."airtable_exercise_record_id" IS 'Original Airtable Record ID of the linked Exercise Library record';



CREATE TABLE IF NOT EXISTS "public"."workout_progress" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "client_id" "text" NOT NULL,
    "workout_id" "text" NOT NULL,
    "block_id" "text" NOT NULL,
    "exercise_id" "text" NOT NULL,
    "set_number" integer,
    "completed_at" timestamp with time zone
);


ALTER TABLE "public"."workout_progress" OWNER TO "postgres";


ALTER TABLE "public"."workout_progress" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."workout_progress_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."workouts" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "airtable_record_id" "text" NOT NULL,
    "preview_video_url" "text",
    "header_image_url" "text",
    "public_workout_title" "text",
    "focus_area" "text",
    "level" "text",
    "duration" "text",
    "block_1_id" "uuid",
    "airtable_block_1_record_id" "text",
    "block_2_id" "uuid",
    "airtable_block_2_record_id" "text",
    "block_3_id" "uuid",
    "airtable_block_3_record_id" "text",
    "block_4_id" "uuid",
    "airtable_block_4_record_id" "text",
    "block_5_id" "uuid",
    "airtable_block_5_record_id" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."workouts" OWNER TO "postgres";


COMMENT ON COLUMN "public"."workouts"."airtable_record_id" IS 'Original Airtable Record ID for sync purposes';



COMMENT ON COLUMN "public"."workouts"."airtable_block_1_record_id" IS 'Original Airtable Record ID of the linked Block 1';



ALTER TABLE ONLY "public"."blocks_overview"
    ADD CONSTRAINT "blocks_overview_airtable_record_id_key" UNIQUE ("airtable_record_id");



ALTER TABLE ONLY "public"."blocks_overview"
    ADD CONSTRAINT "blocks_overview_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."exercise_library"
    ADD CONSTRAINT "exercise_library_airtable_record_id_key" UNIQUE ("airtable_record_id");



ALTER TABLE ONLY "public"."exercise_library"
    ADD CONSTRAINT "exercise_library_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."individual_blocks"
    ADD CONSTRAINT "individual_blocks_airtable_record_id_key" UNIQUE ("airtable_record_id");



ALTER TABLE ONLY "public"."individual_blocks"
    ADD CONSTRAINT "individual_blocks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workout_progress"
    ADD CONSTRAINT "workout_progress_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."workout_progress"
    ADD CONSTRAINT "workout_progress_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_airtable_record_id_key" UNIQUE ("airtable_record_id");



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "set_timestamp_blocks_overview" BEFORE UPDATE ON "public"."blocks_overview" FOR EACH ROW EXECUTE FUNCTION "public"."trigger_set_timestamp"();



CREATE OR REPLACE TRIGGER "set_timestamp_exercise_library" BEFORE UPDATE ON "public"."exercise_library" FOR EACH ROW EXECUTE FUNCTION "public"."trigger_set_timestamp"();



CREATE OR REPLACE TRIGGER "set_timestamp_individual_blocks" BEFORE UPDATE ON "public"."individual_blocks" FOR EACH ROW EXECUTE FUNCTION "public"."trigger_set_timestamp"();



CREATE OR REPLACE TRIGGER "set_timestamp_workouts" BEFORE UPDATE ON "public"."workouts" FOR EACH ROW EXECUTE FUNCTION "public"."trigger_set_timestamp"();



ALTER TABLE ONLY "public"."individual_blocks"
    ADD CONSTRAINT "individual_blocks_block_overview_id_fkey" FOREIGN KEY ("block_overview_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."individual_blocks"
    ADD CONSTRAINT "individual_blocks_exercise_id_fkey" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercise_library"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_block_1_id_fkey" FOREIGN KEY ("block_1_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_block_2_id_fkey" FOREIGN KEY ("block_2_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_block_3_id_fkey" FOREIGN KEY ("block_3_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_block_4_id_fkey" FOREIGN KEY ("block_4_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."workouts"
    ADD CONSTRAINT "workouts_block_5_id_fkey" FOREIGN KEY ("block_5_id") REFERENCES "public"."blocks_overview"("id") ON DELETE SET NULL;





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."trigger_set_timestamp"() TO "anon";
GRANT ALL ON FUNCTION "public"."trigger_set_timestamp"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."trigger_set_timestamp"() TO "service_role";



























GRANT ALL ON TABLE "public"."blocks_overview" TO "anon";
GRANT ALL ON TABLE "public"."blocks_overview" TO "authenticated";
GRANT ALL ON TABLE "public"."blocks_overview" TO "service_role";



GRANT ALL ON TABLE "public"."exercise_library" TO "anon";
GRANT ALL ON TABLE "public"."exercise_library" TO "authenticated";
GRANT ALL ON TABLE "public"."exercise_library" TO "service_role";



GRANT ALL ON TABLE "public"."individual_blocks" TO "anon";
GRANT ALL ON TABLE "public"."individual_blocks" TO "authenticated";
GRANT ALL ON TABLE "public"."individual_blocks" TO "service_role";



GRANT ALL ON TABLE "public"."workout_progress" TO "anon";
GRANT ALL ON TABLE "public"."workout_progress" TO "authenticated";
GRANT ALL ON TABLE "public"."workout_progress" TO "service_role";



GRANT ALL ON SEQUENCE "public"."workout_progress_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."workout_progress_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."workout_progress_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."workouts" TO "anon";
GRANT ALL ON TABLE "public"."workouts" TO "authenticated";
GRANT ALL ON TABLE "public"."workouts" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
